### ISSUE TITLE
Error parsing NBT: NaN value in double tag

### ISSUE THREAD

**Issue by VADemon** [midnightfreddie/nbt2json#2]
`Error parsing NBT: TagType not recognized`
[Player644-NaN.zip](https://github.com/midnightfreddie/nbt2json/files/3438510/Player644-NaN.zip)

It probably occurs because this players position.Y is set to NaN

Thanks a lot for this tool

**Comment by midnightfreddie** [comment]
Thanks! I'll take a look at it.

**Comment by midnightfreddie** [comment]
Good catch. The JSON conversion isn't surfacing the error properly, and it's reading the Y float64 as NaN. Will have to see if I need extra conversion from Java's float64 to Go's float64 or if NaN is a valid position.
