### ISSUE TITLE
Empty array leads to error

### ISSUE THREAD

**Issue by FlufflesTheDog** [midnightfreddie/nbt2json#6]
Attempting to convert a player data file back to NBT results in the following error:
`Error parsing json2nbt: While writing Compound tags: Error parsing json2nbt: While writing Compound tags: Error parsing json2nbt: Tag Compound value field not an array`

I'm not remarkably familiar with how this all works, but it appears a new field is in the newest version of MC; an array with name `memories` which as of testing, ends up with `"value": null` in the json. Changing it to `"value": []` appears to work fine.

Versions:
nbt2json 0.3.0
MC Java Edition 1.15.1, works fine on 1.13.2 and 1.14.4

**Comment by midnightfreddie** [comment]
Hi, thanks for the report! It being the holidays, it may take me a little while to investigate and fix.

**Comment by VADemon** [comment]
Bump. Minecraft expects an empty compound tag at this place, `null` in its place breaks round-trip saving of NBT.

**Comment by midnightfreddie** [comment]
Yeah, I guess I should update the repo. I should have time given the, uh, global environment lately.
