### ISSUE TITLE
Add option to recompress

### ISSUE THREAD

**Issue by VADemon** [midnightfreddie/nbt2json#8]
Recompress the raw NBT back to GZIP. Minecraft doesn't seem to accept raw NBT at all (w00t).

MCPE level.dat header isn't hard to recreate too:

> The file begins with an 8-byte header, consisting of a little-endian 4-byte integer indicating the type of the file, which is 3 (was 2 before latest update) for level.dat. It is followed by another integer containing the length of the file, minus the header.[Minecraft Wiki](https://minecraft.gamepedia.com/Bedrock_Edition_level_format#cite_note-4)

PS: Meanwhile for everyone else use the GNU™® gzip utility.

**Comment by midnightfreddie** [comment]
Adding Gzipping should be trivial. I haven't messed with MC in a while so I'll have to refamiliarize myself with the level.dat header. And my code :).
